services:
  nginx:
    container_name: app
    image: nginx:1.26.2
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./dist:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    environment:
      - TZ=Asia/Seoul
