services:
  nginx:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    image: app:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /data/log/nginx:/var/log/nginx
    environment:
      - TZ=Asia/Seoul
